apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: three-tier
type: Opaque
data:
  username: YWRtaW4=         # admin (base64)
  password: YWRtaW5hZG1pbgo=     # adminadmin (base64)
