version: 0.2

phases:
  pre_build:
    commands:
      - cd Application-Code/backend
      - REPOSITORY_URI=137068239975.dkr.ecr.us-east-1.amazonaws.com/backend
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > ../../backend-imageDetail.json
artifacts:
  files:
    - backend-imageDetail.json
